version: '3.4'
services:
  coordinator:
    build:
      context: ..
      dockerfile: coordinator/Dockerfile
      target: runtime
  example-job-1:
    build:
      context: ..
      dockerfile: example/Dockerfile
      target: runtime
    environment:
      COORDINATOR_HOST: coordinator
  example-job-2:
    build:
      context: ..
      dockerfile: example/Dockerfile
      target: runtime
    environment:
      COORDINATOR_HOST: coordinator