version: '3.4'
services:
  zookeeper:
    image: zookeeper
  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "distroboy.example.topic:8:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  localstack:
    image: localstack/localstack:2.0.2
    environment:
      - SERVICES=${SERVICES-sqs}
      - LS_LOG=${LS_LOG-debug}
    volumes:
      - "./create-bucket.sh:/etc/localstack/init/ready.d/create-bucket.sh"