name: Publish JARs

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Build with Gradle
        run: gradle -Pversion_string=${{ github.ref_name }} -Pcommit_sha=${{ github.sha }} jar
      - name: Publish to GitHub Packages
        run: gradle -Pversion_string=${{ github.ref_name }} -Pcommit_sha=${{ github.sha }} publishAllPublicationsToGitHubPackagesRepository
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}